# This file was generated by GoReleaser. DO NOT EDIT.
cask "knit" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "5c8c4d5baf8ccc19f7f429b7281f20e294d4b7a1a80cc4f2da4e75fdbdf1e0db"
      url "https://github.com/rnwolfe/knit/releases/download/v#{version}/knit_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7152eeee03e76e63d60a7df1504f264c70b144d09f190b796b309fd788ca961f"
      url "https://github.com/rnwolfe/knit/releases/download/v#{version}/knit_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "966287032797d02621f4056265df7ce292e728983cc4630c28fcd98eda3e84fb"
      url "https://github.com/rnwolfe/knit/releases/download/v#{version}/knit_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "48e05b0f6a95f1d93adb19a96f7adb9d6379fb5714d9acdf9d402f1f9338b92c"
      url "https://github.com/rnwolfe/knit/releases/download/v#{version}/knit_linux_arm64.tar.gz"
    end
  end

  name "knit"
  desc "Agent-friendly CLI for Instagram's Threads — read-only by default."
  homepage "https://github.com/rnwolfe/knit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "knit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/knit"]
    end
  end

  # No zap stanza required

end
