# This file was generated by GoReleaser. DO NOT EDIT.
cask "knit" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "a9d7d77b2ec8d39ca21ba42d3b27b0aba80a881d11e740e7cf503cfb0a18b2d0"
      url "https://github.com/rnwolfe/knit/releases/download/v#{version}/knit_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "afa1d58681e9c9db81194d180408768c250ab069cf7144f1f8e61081a3e4660a"
      url "https://github.com/rnwolfe/knit/releases/download/v#{version}/knit_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "de4ddc91bcc1d080d2118472139e786778acf395d6a006b8453fee683b90487f"
      url "https://github.com/rnwolfe/knit/releases/download/v#{version}/knit_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8815ed10c4daf9df5da62800881c10fe76549b213baeda0cd25783368fd2b1d3"
      url "https://github.com/rnwolfe/knit/releases/download/v#{version}/knit_linux_arm64.tar.gz"
    end
  end

  name "knit"
  desc "Agent-friendly CLI for Instagram's Threads — read-only by default."
  homepage "https://github.com/rnwolfe/knit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "knit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/knit"]
    end
  end

  # No zap stanza required

end
