# This file was generated by GoReleaser. DO NOT EDIT.
cask "knit" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "b5904f75c832bb85a6dd1d3ad13adf140b51974f49debbac8e242fe669fcc89e"
      url "https://github.com/rnwolfe/knit/releases/download/v#{version}/knit_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "12ba12283ab0f8adf91c668ac051bac117a2e1ce24ceb20a1f00c38adc1541e2"
      url "https://github.com/rnwolfe/knit/releases/download/v#{version}/knit_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6bc24d7f4ece62a15cd0a283384614928f60228001cccc5a2114eddb3ad783d6"
      url "https://github.com/rnwolfe/knit/releases/download/v#{version}/knit_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c241a7ae494e97766fb623d7a501a2dd5791b97d5e512ca3066330f47db47552"
      url "https://github.com/rnwolfe/knit/releases/download/v#{version}/knit_linux_arm64.tar.gz"
    end
  end

  name "knit"
  desc "Agent-friendly CLI for Instagram's Threads — read-only by default."
  homepage "https://github.com/rnwolfe/knit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "knit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/knit"]
    end
  end

  # No zap stanza required

end
