# This file was generated by GoReleaser. DO NOT EDIT.
cask "rivr" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "7080a13585eda9a2389fab8730db27acf55eb3bf763dee1b83d5e6ae537ebe97"
      url "https://github.com/rnwolfe/rivr/releases/download/v#{version}/rivr_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/rnwolfe/rivr/"
    end
    on_arm do
      sha256 "1152bf8d812c8cdcc88817664bd059e4f4a496d27af1a85cc0d9440b72458c07"
      url "https://github.com/rnwolfe/rivr/releases/download/v#{version}/rivr_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/rnwolfe/rivr/"
    end
  end

  on_linux do
    on_intel do
      sha256 "2605c3452d14c2ed8c7da82458c828531bd64024afd7de0ff99e45c8dfe7fac5"
      url "https://github.com/rnwolfe/rivr/releases/download/v#{version}/rivr_#{version}_linux_amd64.tar.gz",
        verified: "github.com/rnwolfe/rivr/"
    end
    on_arm do
      sha256 "888e70455623bef1e142b3f59624f03f2d5a3cb20e75519274d5bfd8433ac80c"
      url "https://github.com/rnwolfe/rivr/releases/download/v#{version}/rivr_#{version}_linux_arm64.tar.gz",
        verified: "github.com/rnwolfe/rivr/"
    end
  end

  name "rivr"
  desc "Read-only Amazon Shopping CLI for AI agents"
  homepage "https://rivr.sh/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rivr"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rivr"] if OS.mac?
  end

  # No zap stanza required

end
