# This file was generated by GoReleaser. DO NOT EDIT.
cask "rivr" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "d3905eb8bf1751f69fcc266704fde0f889091b420271e9a41609deceaa6ade97"
      url "https://github.com/rnwolfe/rivr/releases/download/v#{version}/rivr_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/rnwolfe/rivr/"
    end
    on_arm do
      sha256 "13352d00cffb9f88c3057c8877a9d2815795ae8cf84bffa9fd7abf659cb22039"
      url "https://github.com/rnwolfe/rivr/releases/download/v#{version}/rivr_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/rnwolfe/rivr/"
    end
  end

  on_linux do
    on_intel do
      sha256 "5ce2abe567ce93df238f7fd87810bde6da2fb6f2b541cca307d065e8e070af17"
      url "https://github.com/rnwolfe/rivr/releases/download/v#{version}/rivr_#{version}_linux_amd64.tar.gz",
        verified: "github.com/rnwolfe/rivr/"
    end
    on_arm do
      sha256 "8725e767fbf0a1868b4cb20e24f5b23a40de98c352666d21d68645135cf23e62"
      url "https://github.com/rnwolfe/rivr/releases/download/v#{version}/rivr_#{version}_linux_arm64.tar.gz",
        verified: "github.com/rnwolfe/rivr/"
    end
  end

  name "rivr"
  desc "Read-only Amazon Shopping CLI for AI agents"
  homepage "https://rivr.sh/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rivr"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rivr"] if OS.mac?
  end

  # No zap stanza required

end
