# This file was generated by GoReleaser. DO NOT EDIT.
cask "rivr" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "6367f2aafc1a5d2c542c17c17ea60f88ee6509e303f3fe8fb35f400d147428bd"
      url "https://github.com/rnwolfe/rivr/releases/download/v#{version}/rivr_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/rnwolfe/rivr/"
    end
    on_arm do
      sha256 "4ad1a5009933cc4f241fa8d265e4e2e22c2a3e49000c93b57610419251374456"
      url "https://github.com/rnwolfe/rivr/releases/download/v#{version}/rivr_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/rnwolfe/rivr/"
    end
  end

  on_linux do
    on_intel do
      sha256 "c46d196d9f732614fa3be950185cf5f15fa233b62fdc8d8531b964f8350c244d"
      url "https://github.com/rnwolfe/rivr/releases/download/v#{version}/rivr_#{version}_linux_amd64.tar.gz",
        verified: "github.com/rnwolfe/rivr/"
    end
    on_arm do
      sha256 "fd22a023bda603dc2b23c44175dad675a100b4424a93b21af22ef9994c3a1f6c"
      url "https://github.com/rnwolfe/rivr/releases/download/v#{version}/rivr_#{version}_linux_arm64.tar.gz",
        verified: "github.com/rnwolfe/rivr/"
    end
  end

  name "rivr"
  desc "Read-only Amazon Shopping CLI for AI agents"
  homepage "https://rivr.sh/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rivr"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rivr"] if OS.mac?
  end

  # No zap stanza required

end
