# This file was generated by GoReleaser. DO NOT EDIT.
cask "vabc" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "6c13925001006e2ada3bbf1791a1f88d6e83954ada7951796083b638d4d95d73"
      url "https://github.com/rnwolfe/vabc/releases/download/v#{version}/vabc_darwin_amd64.tar.gz",
        verified: "github.com/rnwolfe/vabc/"
    end
    on_arm do
      sha256 "2caee0da3155d91898c0f5e2649151288a053cb94501d965ea9b5155a0197b5e"
      url "https://github.com/rnwolfe/vabc/releases/download/v#{version}/vabc_darwin_arm64.tar.gz",
        verified: "github.com/rnwolfe/vabc/"
    end
  end

  on_linux do
    on_intel do
      sha256 "06e8e31f2eb6ec5ed9e7873d9df3a52f18812d3250cf3033b326a32e514a0ad7"
      url "https://github.com/rnwolfe/vabc/releases/download/v#{version}/vabc_linux_amd64.tar.gz",
        verified: "github.com/rnwolfe/vabc/"
    end
    on_arm do
      sha256 "d76c8d654a43226c31bf75d5e2e80ff85bedb0576763cfa738d678afe115de71"
      url "https://github.com/rnwolfe/vabc/releases/download/v#{version}/vabc_linux_arm64.tar.gz",
        verified: "github.com/rnwolfe/vabc/"
    end
  end

  name "vabc"
  desc "Search Virginia ABC products and check store inventory from the command line"
  homepage "https://github.com/rnwolfe/vabc/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vabc"

  postflight do
    if OS.mac?
      system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/vabc"
    end
  end

  # No zap stanza required

end
