# This file was generated by GoReleaser. DO NOT EDIT.
cask "vabc" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "062f0206e6a65c9b1a7bc6531225df50c2adba4073a70eb76a7f0fee3415c99e"
      url "https://github.com/rnwolfe/vabc/releases/download/v#{version}/vabc_darwin_amd64.tar.gz",
        verified: "github.com/rnwolfe/vabc/"
    end
    on_arm do
      sha256 "99dd47c66c2763b601605c9dccbcca3a234f8ea3108d2f9705727179e375229c"
      url "https://github.com/rnwolfe/vabc/releases/download/v#{version}/vabc_darwin_arm64.tar.gz",
        verified: "github.com/rnwolfe/vabc/"
    end
  end

  on_linux do
    on_intel do
      sha256 "c59c7c26efb5303682c0ac0211ba936d99b398579d254c56b8ed9040e12ba3c1"
      url "https://github.com/rnwolfe/vabc/releases/download/v#{version}/vabc_linux_amd64.tar.gz",
        verified: "github.com/rnwolfe/vabc/"
    end
    on_arm do
      sha256 "31e46e90d52b6413a1b88ffb2b128891683060cfcaa6cf114fcf9f474361c21d"
      url "https://github.com/rnwolfe/vabc/releases/download/v#{version}/vabc_linux_arm64.tar.gz",
        verified: "github.com/rnwolfe/vabc/"
    end
  end

  name "vabc"
  desc "Search Virginia ABC products and check store inventory from the command line"
  homepage "https://github.com/rnwolfe/vabc/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vabc"

  postflight do
    if OS.mac?
      system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/vabc"
    end
  end

  # No zap stanza required

end
