# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rivr < Formula
  desc "Read-only Amazon Shopping CLI for AI agents"
  homepage "https://rivr.sh/"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rnwolfe/rivr/releases/download/v0.4.0/rivr_0.4.0_darwin_amd64.tar.gz"
      sha256 "78f8775a89dc6e1c6b4633893d1a1a1e94d0ec142a18046e80147ccc9dcdac32"

      define_method(:install) do
        bin.install "rivr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rnwolfe/rivr/releases/download/v0.4.0/rivr_0.4.0_darwin_arm64.tar.gz"
      sha256 "f0a4988f5f8ca4639e340279102e4b1d815e5e9e9bd481a4c28c0aca30e7df0f"

      define_method(:install) do
        bin.install "rivr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rnwolfe/rivr/releases/download/v0.4.0/rivr_0.4.0_linux_amd64.tar.gz"
      sha256 "4c68223b089afe74e308eaf252a2cd73acc34ec7bd9a5ebb2d391210cfe578d7"
      define_method(:install) do
        bin.install "rivr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rnwolfe/rivr/releases/download/v0.4.0/rivr_0.4.0_linux_arm64.tar.gz"
      sha256 "aedfd8460d1d318716286ada2afd542d15f760210ad503e7d2a4dd928ea94222"
      define_method(:install) do
        bin.install "rivr"
      end
    end
  end

  test do
    system "#{bin}/rivr", "version"
  end
end
