# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rivr < Formula
  desc "Read-only Amazon Shopping CLI for AI agents"
  homepage "https://rivr.sh/"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rnwolfe/rivr/releases/download/v0.3.1/rivr_0.3.1_darwin_amd64.tar.gz"
      sha256 "fa519dc284f8ff76e45ede4d9250b06ce6baac68f2092a07f1fe233c5cac3220"

      define_method(:install) do
        bin.install "rivr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rnwolfe/rivr/releases/download/v0.3.1/rivr_0.3.1_darwin_arm64.tar.gz"
      sha256 "7c4e58d2b29ded375ca5fc91814d1b67e25d92c7966f4cafbeac976f41774d9e"

      define_method(:install) do
        bin.install "rivr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rnwolfe/rivr/releases/download/v0.3.1/rivr_0.3.1_linux_amd64.tar.gz"
      sha256 "72900b0dfe812823e30ff61df7795f9aedb381988c55c44fd2c20d2c121e0ae1"
      define_method(:install) do
        bin.install "rivr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rnwolfe/rivr/releases/download/v0.3.1/rivr_0.3.1_linux_arm64.tar.gz"
      sha256 "ea422f56fed47205d55cec977681c08cd80dbb60e53ba64385c4327aab2cfa19"
      define_method(:install) do
        bin.install "rivr"
      end
    end
  end

  test do
    system "#{bin}/rivr", "version"
  end
end
